### PR TITLE
Save the Log file in same DIR as PHP agent.

### PR DESCRIPTION
**Pull request by Dark1z**
Save the Log `hetrixtools_agent.log` file in same Directory as HetrixTools Server Monitoring Agent (PHP) `hetrixtools_agent.php` file.

So that it does not store in arbitrary directory in shared web hosting server,
Where user may not have access to that Directory.

Best regards 👍

### CODE REVIEW

**Comment by Dark1z** [comment]
@hetrixtools ,

should I add Date & time in beginning of line , like : `[12-May-2019 18:26:00 UTC] ...` .
Example Commit : https://github.com/dark-1/agent-php/commit/a3487771d50448149204452acd32e5b2bd557042

Best regards 👍

**Comment by Dark1z** [comment]
@hetrixtools ,

Any thoughts on above comment ???
https://github.com/hetrixtools/agent-php/pull/4#issuecomment-491618565

Best regards 👍

**Comment by hetrixtools** [comment]
Hello,

Not seeing any point in the log having a timestamp considering the fact that the log file gets overwritten every minute (ie: it doesn't save the log for multiple minutes), so the timestamp is the last time the file has been modified.

Thanks for your contribution.

**Comment by Dark1z** [comment]
@hetrixtools ,

Yea!! I was just trying to make it user-friendly & user convenience as you don't require to check the timestamp in Directory but in the file it's self.

Best regards 👍

**Pull request merged**
